[tool.poetry]
name = "zoku"
version = "0.1.0"
description = ""
authors = ["chrissaher"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
