# Build Sphinx documentation on pull requests targeting main or on the
# main branch. If on the main branch, also deploy built docs to Pages.

name: build_and_host_docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Cancel existing runs when new jobs are spawned from the same branch, excepting main.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build_and_host_docs:
    runs-on: ubuntu-latest

    permissions:
      # Bless GITHUB_TOKEN with Pages rights and verify deployment origin
      # https://docs.github.com/en/pages/getting-started-with-github-pages/using-custom-workflows-with-github-pages#deploying-github-pages-artifacts
      contents: read
      pages: write
      id-token: write

    steps:
      - name: checkout
        uses: actions/checkout@v3
        # with:
        #   token: ${{ secrets.GH_PAT }}
        #   submodules: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Generate documentation
        run: |
          poetry run sphinx-build -b html docs/source docs/build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.SECRET_TOKEN }}
          publish_dir: docs/build
